### ISSUE TITLE
Enhancement of Left navigation

### ISSUE THREAD

**Issue by olakara** [olakara/JekyllMetro#20]
Provide better layout of the left navigation:
1. Needs better alignment 
2. show selected menu as active
3. provide better UI/UX

**Comment by olakara** [comment]
Few enhacements have been done as part of https://github.com/olakara/JekyllMetro/pull/26 pull request.

**Comment by ZhuFengdaaa** [comment]
Is this finished? or have further require?

**Comment by olakara** [comment]
for now, need to hi-light the active menu item. I think that's only needed to complete.

**Comment by ZhuFengdaaa** [comment]
When mouse hovering, it will highlight? I don't know if you meant by that?

**Comment by olakara** [comment]
Completed as part of version 0.8
