### ISSUE TITLE
CSS does not apply in mobile view

### ISSUE THREAD

**Issue by aliyeysides** [olakara/JekyllMetro#27]
Hey great theme, but viewing the site on mobile doesn't show any applied css. 

Here's my repo:
https://github.com/aliyeysides/aliyeysides.github.io

**Comment by olakara** [comment]
@aliyeysides , thanks for trying out JekyllMetro. I did have a look at your site at aliyeysides.github.io. I noticed that you have not configured your _config.yml file properly.. the url property still points to url: 'http://localhost:4000' which we use for development and hosting on a local machine. When you host on github, you will need to appropriately change it. For example on my site its; 'http://abdelraoof.com' .. you will have to replace it to aliyeysides.github.io in your case..

**Comment by aliyeysides** [comment]
Turns out it needed to be blank
