### ISSUE TITLE
Complete the Search model

### ISSUE THREAD

**Issue by ZhuFengdaaa** [olakara/JekyllMetro#30]
Complete the Site Search Function

**Comment by olakara** [comment]
Need more details.. What are you planning to implement?

**Comment by ZhuFengdaaa** [comment]
Yes, I am willing to do so. Let's discuss about how we should do with it?

**Comment by olakara** [comment]
ok, we can discuss.. What are you planning to implement? something related to UI or some functionality?

**Comment by ZhuFengdaaa** [comment]
How about using Google site search, or we make it by ourself?

2015-02-09 11:32 GMT+08:00 Abdel Raoof <notifications@github.com>:
