### ISSUE TITLE
Tags links is broken 

### ISSUE THREAD

**Issue by boban-radeski** [olakara/JekyllMetro#31]
On some tags when I click it gives me 404 error.

**Comment by olakara** [comment]
@boban-radeski , for tags you will have to create your own folder and copy the necessary files and do some tweaking. Unfortunately, this is a manual process.

 For example, have a look at tags folder in repository. You have "SharePoint" folder with HTML templates to display necessary details about the tag. Surely there is some better way.. but for now, that's how it is.
