### ISSUE TITLE
"Back To Top" button overlapping the button

### ISSUE THREAD

**Issue by olakara** [olakara/JekyllMetro#32]
Back to top button overlapping the button when scroll bar at the end:
![overlapping](https://cloud.githubusercontent.com/assets/570905/6764652/b6de0b72-cf78-11e4-883f-e2da7c4f0d41.png)

**Comment by ZhuFengdaaa** [comment]
So I suggested that the entries should be 3/4 width of the whole page.
[see my blog](http://zhufengdaaa.github.io/blog/)

**Comment by olakara** [comment]
Fixed on development1.0 branch..
