### ISSUE TITLE
Custom Font Use

### ISSUE THREAD

**Issue by GizmoCodes** [olakara/JekyllMetro#37]
I'm trying to use Google Fonts, and I added this to my head.html:
```CSS selector {
  font-family: 'Font Name', serif;
}```
But now I don't know where to put this:
```font-family: 'Source Sans Pro', sans-serif;```
I assume its in another CSS file, but I don't know. Anyone know?

**Comment by olakara** [comment]
Hi @GizmoCodes , you can place your custom CSS in app.css file available under [assets/css/](https://github.com/olakara/JekyllMetro/tree/master/assets/css) folder. Apart from this, you will need to add link to your google fonts. This can be done in [head.html](https://github.com/olakara/JekyllMetro/blob/master/_includes/head.html).. I already have a Google font at line 69.. you just need to change it according to your font.
