### ISSUE TITLE
Merge artifacts in index.html and _includes/svg-icons.html

### ISSUE THREAD

**Issue by mwmahlberg** [olakara/JekyllMetro#40]
In both files, there are unresolved merge conflicts committed.

* Line#s in index.html: 111,113 and 117
* Line#s in _includes/svg-icons.html: 1,14,27

Since I am not sure which parts are intended to include and exclude, I could not fix that and send a pull request.

**Comment by olakara** [comment]
Thanks for pointing it out.. I have fixed it..
