### ISSUE TITLE
Search does not seem to work with Jekyll 3.0.0

### ISSUE THREAD

**Issue by mwmahlberg** [olakara/JekyllMetro#41]
When using the search page, a `search.son` document is requested, which does not seem to get generated, as the server returns a 404 error and the document does exist in the generated tree (nor somewhere else).

Maybe this is my fault, since I do not have taken any additional steps to create it.

**Comment by olakara** [comment]
Hi @mwmahlberg , thanks for pointing it out. I missed out a whole file named search.json. I have added the template in the latest commit! This should solve the problem :)

**Comment by mwmahlberg** [comment]
Put the file into the wrong directory. Send pull request #42 to fix this and another minor issue with backwards compatibility
