### ISSUE TITLE
problem when jekyll converts JekyllMetro site

### ISSUE THREAD

**Issue by bilardi** [olakara/JekyllMetro#44]
I forked your site and I tested to change the url and baseurl options into _config.yml file because I'd like to use your theme for a non-profits organization site.
The test is into [bilardi/JekyllMetroTest](https://github.com/bilardi/JekyllMetroTest) and I'd like to visualize it in https://bilardi.github.io/JekyllMetroTest. 
Does your theme work with the github page and the jekyll automation?
Can you help me find where am I wrong?
Thank you.

**Comment by olakara** [comment]
Hi, thanks for posting the issue. There might be some issues with Jekyll 3.x.. I haven't tested my theme for Jekyll 3.x version due to lack of time. I test and let you know if there is any issues. 

In the mean time, could you please explain what issue you were facing when trying out the theme?

**Comment by bilardi** [comment]
I learned I can fork your project, change some configuration in _config.yml, digit a site for the new project, like https://bilardi.github.io/JekyllMetroTest, and then it will be calculated by Jekyll with a github pages automation and I will see the site in https://bilardi.github.io/JekyllMetroTest. This method had worked for others themes.

Your theme doesn't work with this method. In this page tells about errors of build: https://help.github.com/articles/troubleshooting-jekyll-builds/ but I don't receive any errors for the new project forked. I didn't try the stand alone mode.

**Comment by bilardi** [comment]
I'm sorry: I didn't read very well the [documentation](https://help.github.com/categories/github-pages-basics/) so I resolved when I created the branch [gh-pages](https://help.github.com/articles/user-organization-and-project-pages/).

Thank you very much for your time.
